name: Provision Fabric Data Platform
on: workflow_dispatch 
# on:
#   push:
#     branches:
#         - main
#     paths:
#         - '**.bicep'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.ACTION_SPN_CLIENTID }}
        client-secret: ${{ secrets.ACTION_SPN_SECRET }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        auth-type: spn

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope
        subscriptionId: ${{ secrets.AZURE_CREDENTIALS }}
        template: iac/bicep/main.bicep
        # parameters: 'k1=v1 k2=v2 k3=v3'
        failOnStdErr: false
