name: Provision Fabric Data Platform
on: workflow_dispatch 
# on:
#   push:
#     branches:
#         - main
#     paths:
#         - '**.bicep'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3

    - name: Debug Secrets
      run: |
        echo "Checking secrets..."
        echo "ACTION_SPN_CLIENTID: ${{ secrets.ACTION_SPN_CLIENTID }}"
        echo "TENANT_ID: ${{ secrets.TENANT_ID }}"
        echo "SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}"


    #Log into Azure
    - uses: azure/login@v1
      with:
           creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'


    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        template: iac/bicep/main.bicep
        # parameters: 'k1=v1 k2=v2 k3=v3'
        deploymentMode: Incremental  # Ensures existing resources remain untouched
        failOnStdErr: false
