name: Deploy Bicep Template with Parameters

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Azure CLI Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install Bicep CLI
      - name: Install Bicep CLI
        run: az bicep install

      # Validate Bicep Syntax
      - name: Validate Bicep Template Syntax
        run: az bicep build --file iac/bicep/main.bicep

      # Optional: Debug Bicep File Location
      - name: Debug Bicep File Location
        run: ls -la iac/bicep

      # Optional: Check if Required Parameters Are Present
      - name: Output Bicepparam File for Debugging
        run: cat iac/bicep/main.bicepparam

      # Validate Parameterized Deployment
      - name: Validate Bicep Deployment with Parameters
        run: |
          az deployment sub validate \
            --location westeurope \
            --template-file iac/bicep/main.bicep \
            --parameters @iac/bicep/main.bicepparam \
            --debug

      # What-If Analysis (Optional Pre-check)
      - name: Preview What-If Deployment
        run: |
          az deployment sub what-if \
            --location westeurope \
            --template-file iac/bicep/main.bicep \
            --parameters @iac/bicep/main.bicepparam \
            --debug

      # Final Bicep Deployment
      - name: Deploy Bicep Template with Parameters
        run: |
          az deployment sub create \
            --location westeurope \
            --template-file iac/bicep/main.bicep \
            --parameters @iac/bicep/main.bicepparam \
            --debug

      # Optional: Deploy using Azure ARM Deploy GitHub Action
      - name: ARM Deploy (Optional)
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          template: iac/bicep/main.bicep
          parameters: iac/bicep/main.bicepparam
          deploymentMode: Incremental
          failOnStdErr: false


